default-lease-time 14400;
max-lease-time 14400;

authoritative;
ddns-update-style interim;
allow booting;
allow bootp;
allow unknown-clients;
ignore client-updates;

subnet 10.0.0.0 netmask 255.255.255.0 {
  option routers 10.0.0.1;
  option subnet-mask 255.255.255.0;
  option domain-name "kube.lan";
  option domain-name-servers 10.0.0.1;
  range 10.0.0.80 10.0.0.99;

}

host kube-cp-1 {
  hardware ethernet 00:0C:29:A4:B1:10;
  fixed-address 10.0.0.201;
}

host kube-cp-2 {
  hardware ethernet 00:0C:29:47:B9:FE;
  fixed-address 10.0.0.202;
}

host kube-cp-3 {
  hardware ethernet 00:0C:29:59:C6:79;
  fixed-address 10.0.0.203;
}

host kube-w-1 {
  hardware ethernet 00:0C:29:E0:34:DF;
  fixed-address 10.0.0.211;
}

host kube-w-2 {
  hardware ethernet 00:0C:29:BF:A1:FC;
  fixed-address 10.0.0.212;
}
